# The authors are ALiza Litvak, Liz Wyatt, Anna Raycroft, Serenity Schuler
import turtle
fred = turtle.Turtle()
fred.color("red")
fred.forward(100)
fred.right(90)
fred.forward(140)
fred.right(90)
fred.forward(100)
fred = turtle.Turtle()
fred.color("blue")
fred.forward(22)
fred.right(76)
fred.forward(30)
fred.right(76)
fred.forward(22)
